DROP SCHEMA IF EXISTS PROMOCIONES;
CREATE SCHEMA PROMOCIONES;
USE PROMOCIONES;

-- Tabla Promocion
DROP TABLE IF EXISTS PROMOCION;
CREATE TABLE PROMOCION(
	ID_PROMOCION INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CIF INT,
    NOMBRE VARCHAR(255),
    PLANO TEXT,
    POBLACION INT,
    UNIQUE (CIF)
);

-- Tabla Vivienda
DROP TABLE IF EXISTS VIVIENDA;
CREATE TABLE VIVIENDA(
	ID_VIVIENDA INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_PROMOCION INT UNSIGNED,
    SUPERFICIE_EN_M2 DOUBLE,
    NUMERO_HABITACIONES INT,
    NUMERO_BANIOS INT,
    PLANO TEXT,
    FOTO TEXT,
    PRECIO_EN_EUROS INT,
    TERRAZA BOOLEAN,
    JARDIN BOOLEAN,
    PISCINA BOOLEAN,
    GARAJE BOOLEAN,
    FOREIGN KEY (ID_PROMOCION) REFERENCES PROMOCION(ID_PROMOCION)
);

-- Tabla Empresa
DROP TABLE IF EXISTS EMPRESA;
CREATE TABLE EMPRESA(
	ID_EMPRESA INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CIF INT,
    NOMBRE VARCHAR(255),
    TIPO TEXT,
    DIRECCION TEXT,
    TELEFONO INT(9),
    FAX INT(9),
    EMAIL TEXT,
    UNIQUE (CIF)

);

-- Tabla Promocion_contrata_empresa
DROP TABLE IF EXISTS PROMOCION_CONTRATA_EMPRESA;
CREATE TABLE PROMOCION_CONTRATA_EMPRESA(
	ID_CONTRATO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_EMPRESA INT UNSIGNED,
    ID_PROMOCION INT UNSIGNED,
    IMPORTE_CONTRATO_EN_EUROS FLOAT,
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA),
    FOREIGN KEY (ID_PROMOCION) REFERENCES PROMOCION(ID_PROMOCION)
);
